shared:
    image: node:8

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - meta: |
                meta set tests.coverage 100
                meta set tests.results 10/10
            - install: npm install
            - test: npm test
