shared:
    image: node:8

cache:
   pipeline: [/tmp/test]

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - copy: |
                echo $SD_TOKEN
                mkdir -p /tmp/test
                cp firefox.dmg /tmp/test/1.dmg
                # cp firefox.dmg /tmp/test/2.dmg
                # cp firefox.dmg /tmp/test/3.dmg
                # cp firefox.dmg /tmp/test/4.dmg
                # cp firefox.dmg /tmp/test/5.dmg
                # cp firefox.dmg /tmp/test/6.dmg
                # cp firefox.dmg /tmp/test/7.dmg
                # cp firefox.dmg /tmp/test/8.dmg
                # cp firefox.dmg /tmp/test/9.dmg
                # cp firefox.dmg /tmp/test/10.dmg
